{
 "title": "Mongo Log",
 "tags": [ "mongo" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "mongo_severity", "label": "Mongo Severity", "query": "F, E, W, I, D1, D2, D3, D4, D5" },
   {
    "name": "job",
    "label": "Service Name",
    "query": {}
   },
   {
    "name": "file",
    "label": "File Name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Pie Chart",
   "type": "piechart",
   "description": "Get query per collection rate",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(collection_name) (count_over_time({job=~\"$job\", filename=~\"$file\"} | json ns=\"attr.ns\" | ns != `` | ns != `admin.$cmd` | ns !~ `^local.*` | ns !~ `^config.*` | ns !~ `.*\\$cmd.*` | ns !~ `^admin.*` | label_format collection_name=\"{{.ns}}\" [1m]))",
     "legendFormat": "{{ collection_name }}"
    }
   ]
  },
  {
   "title": "Collection Query Rate",
   "type": "timeseries",
   "description": "Get query per collection rate",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(collection_name) (count_over_time({job=~\"$job\", filename=~\"$file\"} | json ns=\"attr.ns\" | ns != `` | ns != `admin.$cmd` | ns !~ `^local.*` | ns !~ `^config.*` | ns !~ `.*\\$cmd.*` | ns !~ `^admin.*` | label_format collection_name=\"{{.ns}}\" [1m]))",
     "legendFormat": "{{ collection_name }}"
    }
   ]
  },
  {
   "title": "Severity Rate",
   "type": "timeseries",
   "description": "Get query per collection rate",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(mongo_severity) (count_over_time({job=~\"$job\", filename=~\"$file\"} | json mongo_severity=\"s\" | mongo_severity =~ `$mongo_severity` [$__auto]))",
     "legendFormat": "{{ collection_name }}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "logs",
   "description": "Query log from mongod",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=~\"$job\", filename=~\"$file\"}\n| json\n| c = \"COMMAND\"\n| attr_ns != \"\"\n| attr_ns != \"admin.$cmd\"\n| attr_ns !~ \"^local.*\"\n| attr_ns !~ \"^config.*\"\n| attr_ns !~ \"^admin.*\"\n| attr_ns !~ \".*\\\\$cmd.*\"\n| json ns=\"attr.ns\", app=\"attr.appName\", find=\"attr.command.find\", filter=\"attr.command.filter\", projection=\"attr.command.projection\", comment=\"attr.command.comment\", sort=\"attr.command.sort\", pipeline=\"attr.command.pipeline\"\n| line_format `{{ printf \"%-30s\" .ns }} {{ printf \"%-30s\" .app }} [Filter : {{ or .filter \"{}\" }}, Projection : {{ or .projection \"{}\" }}, Sort : {{ or .sort \"{}\" }}, Pipeline : {{ or .pipeline \"[]\" }}] {{ printf \"%-50s\" .comment }}`"
    }
   ]
  },
  {
   "title": "Mongod Logs",
   "type": "logs",
   "description": "Query log from mongod",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=~\"$job\", filename=~\"$file\"} |= ``"
    }
   ]
  }
 ]
}